version: '3.9'

services:

  postgres:
    image: postgres:16

    container_name: payments-db

    env_file:
      - .env

    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .

    container_name: microserviciointegrador-app

    depends_on:
      postgres:
        condition: service_healthy

    ports:
      - "8080:8080"

    env_file:
      - .env

    environment:
      SPRING_PROFILES_ACTIVE: docker

    restart: unless-stopped

volumes:
  postgres_data: